[ko]
  title = "FalcoN's Study Blog"
  languageName = "한국어"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ko"


[en]
  title = "FalcoN's Study Blog"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"

