logoText = "FalcoN"
logoType = "short" # long, short
description = "FalcoN의 공부한 내용을 정리하는 블로그입니다."
custom_css = []
custom_js = []
useFaviconGenerator = false # https://www.favicon-generator.org/
meta_image = ""
themecolor = ""

themeOptions = ["light", "dark", "solarized", "hacker", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

enableUiAnimation = true

# header
homeHeaderType = "text" # text, img, slide

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 20
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20

# whoami
myname = "FalcoN"
email = "inhyok2003@naver.com"
whoami = "📚Learner"
bioImageUrl = ""
useGravatar = false
location = "Incheon, Korea"
organization = "INU"
link = "https://FalcoN1995.github.io/ko"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "outer" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "left"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = false
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = false
disqus_shortname = ""
commento = false

[utterances]       # https://utteranc.es/
  owner = "FalcoN1995"              # Your GitHub ID
  repo = "blog"               # The repo to store comments

[socialOptions]
  email = "mailto:inhyok2003@naver.com"
  # phone = ""
  # facebook = "http://example.org/"
  # twitter = "http://example.org/"
  github = "https://github.com/FalcoN1995"
  # stack-overflow = ""
  # instagram = ""
  # youtube = ""
  # linkedin = ""
  # csdn = ""
  # gitlab = ""

[[footerLinks]]
  name = ""
  link = ""
  
[[footerLinks]]
  name = ""
  link = ""